# -*- coding: utf-8 -*-
"""Letsupgrade Python Assignment.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8w2ynUkRL8kF4AAVQwi409bQf3x4s7G
"""



num = int(input("Enter the integer number"))

if(num%2)==0:
  print(num ," it is an even number")
else:
  print(num ," it is an odd number")

#write a program to find out the input number is prime or not 
num = int(input("Enter any positive number to check it is prime or not"))
if num>1:
  for i in range(2,num):
    if(num%i)==0 :
      print(num,"it is not a prime number")
      break
  else:
    print(num, "it is a prime number")
else :
  print(num,"is not a prime number")